### ISSUE TITLE
这个爬虫规则可以简单介绍下吗

### ISSUE THREAD

**Issue by stiangao** [callmelanmao/yunshare#1]
比如启点是什么？怎么爬下一个连接

**Comment by callmelanmao** [comment]
过几天会更新下README.md文件，这几天有其他事情要处理，请等等，

**Comment by callmelanmao** [comment]
@stiangao 爬虫模型挺简单的，你可以看我写的最新的这篇博客，[https://lanmaowz.com/simple-node-model/](简单高效的nodejs爬虫模型)
